;--------------------------
;Title: "Initialisation File" for cheat companion app
;Author: TKBS
;Date: 2026
;Not finished, the only LINE required is "NoFallDMG=" (NFD)
;Nothing else has been implemented.
;See source code to do the rest, 
;Example: IF Maxskills button is pressed set value here to 1
;	  IF value is 1 here on Boot then disable MaaxSkills button (already used)	
;Info;-
;to store and load cheat status.
;primarily to avoid dynamic address (DA) issues.
;when the NoFallDMG, dynamic address, is found it will be stored in this file.
;NoFallDMG=0 Test spaces banana 123 #!
;--------------------------
50hz=0
60hz=0
PEE=0
VHID=457
Moon=0
Collectibles=0
100%=0
MaxSkills=0
Cars_Invisible=0
Cars_Fly=0
Cars_Water=0
Cars_Black=0
Cars_Pink=0
DriveBy=0
FastClock=0
Inf_Ammo=0
Inf_Health=0
Inf_O2=0
Inf_Sprint=0
PIMP=0
NoHunger=0
SuperJump=0
NoFallDMG=0
;^^Dynamic(NFD)Addresses
Inf_Ammo2=0
NumTimesCheated=0
ColourEffects=0
Bloom=0
Fog=0
Radiosity=0
Vision_Night=0
Vision_Thermal=0
colourFilter=0
